# Generated by Django 4.2.2 on 2023-07-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='tour_images/'),
        ),
    ]
